### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by ronangaillard** [marckhoury/youtubewatchstats#1]
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
`heroku logs --tail`

**Comment by marckhoury** [comment]
Hi Ronan. Thanks for contacting me. I'm aware that the page can no longer be served, I took the web dyno down. I ran into two unexpected bugs while parsing watch histories, and I had no other way to alert people that they should stop waiting other than to take down the service. I intend to put it back up after I understand what happened.

**Comment by marckhoury** [comment]
Everything is back up.
